CREATE TABLE IF NOT EXISTS TRANSACTION (
	TRANSACTION_ID integer not null auto_increment, 
	TRANSACTION_TYPE varchar(255), 
	AMOUNT float,
	TRANSACTION_DATE date,
	ACCOUNT_ID integer,
	BALENCE_BEFOR float,
	BALENCE_AFTER float,
	primary key (TRANSACTION_ID)) ;
	
alter table TRANSACTION add constraint foreign key (ACCOUNT_ID) references ACCOUNT (ACCOUNT_ID);

INSERT INTO USER( TRANSACTION_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_DATE, ACCOUNT_ID, BALENCE_BEFOR, BALENCE_AFTER) VALUES
	(1, 'deposit', 20, '12/05/2022',1,80,100)

